const faqs = [
    {
        question: 'What is LocalMoco?',
        answer: 'LocalMoco is an AI-powered survey builder that helps businesses create effective surveys from simple, goal-oriented prompts. It streamlines the process of gathering user feedback and market insights.',
    },
    {
        question: 'How is LocalMoco different from other survey tools?',
        answer: 'Our key differentiator is the use of generative AI. Instead of you having to write every question, our AI generates a survey for you based on your research goals. This saves you time and helps you create more effective surveys.',
    },
    {
        question: 'Who is LocalMoco for?',
        answer: 'LocalMoco is designed for businesses, entrepreneurs, product managers, and marketers who need to gather user feedback quickly and efficiently to validate ideas, understand customer needs, and make data-driven decisions.',
    },
    {
        question: 'How do I share my survey and collect responses?',
        answer: "Once your survey is ready, you'll get a unique, shareable link. You can distribute this link across your own channels, like email, social media, or your website, to start collecting responses.",
    },
    {
        question: 'How can I see my survey results?',
        answer: 'As responses come in, they populate your dashboard in real-time, where you can view and analyze the data to uncover insights.',
    },
    {
        question: 'Can I customize the surveys generated by the AI?',
        answer: 'Yes, absolutely. The AI-generated survey is a starting point. You have full control to edit, add, or remove questions to ensure the survey perfectly fits your needs.',
    },
    {
        question: 'How much does LocalMoco cost?',
        answer: 'We offer a variety of plans to fit your needs, including a free plan to get you started. You can find more details on our <a href="/pricing" class="font-semibold text-[#E27A70] hover:text-[#E27A70CC] dark:text-[#E27A70] dark:hover:text-[#E27A70CC]">pricing page</a>.',
    },
]

export default function FaqSection() {
	return (
		<div className="bg-white dark:bg-gray-900">
			<div className="mx-auto max-w-7xl px-6 py-24 sm:pt-32 lg:px-8 lg:py-40">
				<div className="lg:grid lg:grid-cols-12 lg:gap-8">
					<div className="lg:col-span-5">
						<h2 className="text-pretty text-3xl font-semibold tracking-tight text-gray-900 sm:text-4xl dark:text-white">
							Frequently asked questions
						</h2>
						<p className="mt-4 text-pretty text-base/7 text-gray-600 dark:text-gray-400">
							Can’t find the answer you’re looking for? Reach out to our{' '}
							              <a
							                href="/contact"
							                className="font-semibold text-[#E27A70] hover:text-[#E27A70CC] dark:text-[#E27A70] dark:hover:text-[#E27A70CC]"
							              >                customer support
              </a>{' '}
							team.
						</p>
					</div>
					<div className="mt-10 lg:col-span-7 lg:mt-0">
						<dl className="space-y-10">
							{faqs.map((faq) => (
								<div key={faq.question}>
									<dt className="text-base/7 font-semibold text-gray-900 dark:text-white">{faq.question}</dt>
									<dd className="mt-2 text-base/7 text-gray-600 dark:text-gray-400" dangerouslySetInnerHTML={{ __html: faq.answer }} />
								</div>
							))}
						</dl>
					</div>
				</div>
			</div>
		</div>
	)
}
